// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5p9y6WjS8PP-TkXtbfuFF3heYQNCYhFM',
    appId: '1:225299067038:web:138227d9addbd8bc65cb8f',
    messagingSenderId: '225299067038',
    projectId: 'strata-lite',
    authDomain: 'strata-lite.firebaseapp.com',
    storageBucket: 'strata-lite.firebasestorage.app',
    measurementId: 'G-NNP85WXMEB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1MQfa-QEu7aO_7UDU4BU6uf6V2ETJDB0',
    appId: '1:225299067038:android:e49fb67a12e7bbdf65cb8f',
    messagingSenderId: '225299067038',
    projectId: 'strata-lite',
    storageBucket: 'strata-lite.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxCwXwri1Hm0yAgpesADuS3K97qtpOwHI',
    appId: '1:225299067038:ios:83aa999695bdbf0d65cb8f',
    messagingSenderId: '225299067038',
    projectId: 'strata-lite',
    storageBucket: 'strata-lite.firebasestorage.app',
    iosBundleId: 'com.example.projekStrataMini',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB5p9y6WjS8PP-TkXtbfuFF3heYQNCYhFM',
    appId: '1:225299067038:web:0fbda7e7ad92258365cb8f',
    messagingSenderId: '225299067038',
    projectId: 'strata-lite',
    authDomain: 'strata-lite.firebaseapp.com',
    storageBucket: 'strata-lite.firebasestorage.app',
    measurementId: 'G-J02YMXSVY7',
  );

}